2018-09-30 20:48:31,922 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:46]
2018-10-01 15:23:51,522 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:46]
2018-10-01 15:25:53,324 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:46]
2018-10-14 12:12:12,415 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:46]
2018-10-14 14:56:37,135 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:46]
2018-10-14 14:57:09,498 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:46]
2018-10-14 23:30:08,825 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:46]
2018-10-15 15:45:41,743 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:46]
2018-11-01 11:40:25,530 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:46]
2018-11-01 12:51:10,226 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:46]
2018-11-01 13:44:42,116 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:46]
2018-11-01 14:15:28,814 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:46]
2018-11-03 16:56:20,991 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:48]
2018-11-10 16:56:23,069 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:50]
2018-11-10 16:57:04,710 ERROR: Exception on /login [GET] [in c:\users\marlon pimentel\microblog\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\users\marlon pimentel\microblog\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\marlon pimentel\microblog\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\marlon pimentel\microblog\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\marlon pimentel\microblog\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\users\marlon pimentel\microblog\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\marlon pimentel\microblog\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Marlon Pimentel\microblog\app\routes.py", line 47, in login
    return render_template('login.html', title="Sign In", form=form)
  File "c:\users\marlon pimentel\microblog\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "c:\users\marlon pimentel\microblog\venv\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "c:\users\marlon pimentel\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\marlon pimentel\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\marlon pimentel\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\marlon pimentel\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Marlon Pimentel\microblog\app\templates\base.html", line 55, in template
    {% block content %}{% endblock %}
  File "c:\users\marlon pimentel\microblog\venv\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\Marlon Pimentel\microblog\app\templates\login.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "c:\users\marlon pimentel\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\marlon pimentel\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Marlon Pimentel\microblog\app\templates\base.html", line 55, in template
    {% block content %}{% endblock %}
  File "c:\users\marlon pimentel\microblog\venv\lib\site-packages\jinja2\environment.py", line 543, in _generate
    optimized=self.optimized)
  File "c:\users\marlon pimentel\microblog\venv\lib\site-packages\jinja2\compiler.py", line 82, in generate
    generator.visit(node)
  File "c:\users\marlon pimentel\microblog\venv\lib\site-packages\jinja2\visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "c:\users\marlon pimentel\microblog\venv\lib\site-packages\jinja2\compiler.py", line 718, in visit_Template
    self.fail('block %r defined twice' % block.name, block.lineno)
  File "c:\users\marlon pimentel\microblog\venv\lib\site-packages\jinja2\compiler.py", line 315, in fail
    raise TemplateAssertionError(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateAssertionError: block 'content' defined twice
2018-11-10 16:58:07,041 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:50]
2018-11-25 20:26:35,930 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:57]
2018-12-09 22:45:34,771 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:57]
2018-12-09 22:46:38,692 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:57]
2018-12-09 22:46:55,183 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:57]
2018-12-10 16:17:32,445 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:57]
2018-12-10 16:18:06,494 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:57]
2018-12-11 22:41:01,469 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:57]
2018-12-13 20:34:05,278 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:57]
2018-12-13 20:35:22,343 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:57]
2018-12-13 20:35:39,123 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:57]
2018-12-13 20:35:54,003 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:57]
2018-12-13 20:52:03,300 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:57]
2018-12-13 21:02:03,479 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:57]
2018-12-13 21:09:39,203 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:57]
2018-12-17 18:10:04,596 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:75]
2018-12-17 18:10:09,354 ERROR: Exception on / [GET] [in c:\users\marlon pimentel\microblog\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\users\marlon pimentel\microblog\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\marlon pimentel\microblog\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\marlon pimentel\microblog\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\marlon pimentel\microblog\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\users\marlon pimentel\microblog\venv\lib\site-packages\flask\app.py", line 1610, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\users\marlon pimentel\microblog\venv\lib\site-packages\flask\app.py", line 1831, in preprocess_request
    rv = func()
  File "C:\Users\Marlon Pimentel\microblog\app\main\routes.py", line 19, in before_request
    g.locale = str(get_locale())
  File "c:\users\marlon pimentel\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 257, in get_locale
    rv = babel.locale_selector_func()
  File "C:\Users\Marlon Pimentel\microblog\app\__init__.py", line 82, in get_locale
    return request.accept_languages.best_match(app.config['LANGUAGES'])
NameError: name 'app' is not defined
2018-12-17 18:12:22,031 INFO: Microblog startup [in C:\Users\Marlon Pimentel\microblog\app\__init__.py:75]
